site_name: 韦光义的小站
site_url: http://198.12.108.120
site_dir: /usr/website/mkdocs_site
nav:
  - 主页: index.md
  - 关于我: about.md
  - 记事: 
    - 如何申请OCBC的实体银行卡（教程）: 2024/03/01.md
    - 三月2: 2024/03/02.md
  - 技术:
    - openssl生成https证书给nginx使用: 2024/03/02.md
theme: readthedocs
