site_name: August的小站
site_url: http://ee4ga9d.xyz
site_dir: /usr/website/mkdocssite
nav:
  - 主页: index.md
  - 关于我: about.md
  - 记事: 
    - 如何申请OCBC的实体银行卡（教程）: 2024/03/01.md 
    - 日本自由行（攻略）: 2024/04/08.md 
    - 美国旅游签申请（攻略）: 2024/08/30.md 
  - 技术:
    - openssl生成https证书给nginx使用: 2024/03/02.md 
    - Go语言学习记录: 2024/07/07.md
theme: readthedocs
